version: '3'

services: 
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    volumes: ['./db_data:/var/lib/mysql']
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: restaurantes
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    networks:
      - lamp
  phpmyadmin:
    depends_on:
      - db
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - lamp
  apache:
    container_name: apache
    build: .
    restart: always
    volumes: ['./www:/var/www/html']
    ports:
      - '8080:80'
    networks:
      - lamp

networks:
  lamp: